resource "tls_private_key" "this" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "aws_ssm_parameter" "this" {
  name        = format("%s/ec2/key_pem", local.ssm_prefix)
  description = "My key-pair private key"
  type        = "SecureString"
  value       = tls_private_key.this.private_key_pem
}

resource "aws_key_pair" "this" {
  key_name   = format("%s-ec2", local.prefix)
  public_key = tls_private_key.this.public_key_openssh

  provisioner "local-exec" { # Generate "terraform-key-pair.pem" in current directory
    command = "echo '${tls_private_key.this.private_key_pem}' > ./'${format("%s-ec2", local.prefix)}'.pem"
  }

  # provisioner "local-exec" {
  #   command = "chmod 400 ./'${format("%s-ec2", local.prefix)}'.pem"
  # }

}

# output "ssh_key" {
#   description = "ssh key generated by terraform"
#   value       = tls_private_key.this.private_key_pem
#   sensitive   = true
# }
